#%RAML 1.0
title: Test api
version: 1
mediaType: application/json
protocols:
  - HTTP
baseUri: /

/:
    get:
        responses:
            200:
                body:
                    type: object
                    properties:
                        message: string

/tasks:
    get:
        responses:
            200:
                body:
                    type: object

/task/{taskid}:
    description: get task by id
    uriParameters:
        taskid:
            type: integer
            example: 3

    get:
        responses:
            200:
                body:
                    type: string

/task:
    get:
        responses:
            200:
    post:
        description: |
            Creates a task
        body:
            application/x-www-form-urlencoded:
                properties:
                    name:
                        description: Nam of the task
                        type: string
                        example: Code things
                    owner:
                        description: Who's going to do it
                        type: string
                        example: Joan
        responses:
            200:

/user/{userid}/task/{taskid}:
    description: Get a task from a user id (Note that the userid is defined and the taskid not)
    uriParameters:
        userid:
            type: integer
            example: 57
    get:
        responses:
            200:
                body:
                    type: string

/url/with/params:
    get:
        queryParameters:
            date_in:
                type: date-only
                required: true
                example: 2016-09-19
            date_out:
                type: date-only
                required: true
                example: 2016-09-19

/task/type/defined:
    get:
        responses:
            200:
                body:
                    type: Task
                    example: !include example_response.json

/unexisting:
    get:
        responses:
            200:
                body:
                    type: string

types:
    Task:
        properties:
            id:
                type: integer
                required: true
            name:
                type: string
                required: true
